# Generated by Django 3.1.7 on 2021-04-03 05:40

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
